name: informer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - pip
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - torchmetrics
  - pytorch-lightning
  - python-dotenv
  - pre-commit
